name: BankerPlus
version: @version@
main: com.horizon.bankerplus.BankerPlus
authors: [Horion, yakovliam]
description: BankerPlus Bukkit plugin

commands:
  bank:
    usage: /bank
    description: Use the Banker+ GUI
